### ISSUE TITLE
可以改进下手机版的样式吗

### ISSUE THREAD

**Issue by eazhijiacom** [bigfa/Farallon#10]
作者你好，主题做的很漂亮哈
手机版上有个问题哈，比如菜单过多的话，就显示不完全了，可以在菜单那里改进下吗，如图

菜单多了就显示不全了：
![QQ截图20240627165858](https://github.com/bigfa/Farallon/assets/172482214/0ef928a9-0d84-4271-bdb0-f11f68a07c78)

可以参照下面的修改下：
![QQ截图20240627165832](https://github.com/bigfa/Farallon/assets/172482214/599d431d-89f7-451e-9b57-793fa6d31a37)

**Comment by bigfa** [comment]
那不是有滚动条吗。。。

**Comment by eazhijiacom** [comment]
> 那不是有滚动条吗。。。

不太好看吧。。。现在手机版的应该都用的三条线的那种了吧

**Comment by bigfa** [comment]
原本设计就是这样的，不满意的话可以自行修改。
