### ISSUE TITLE
卡片分类页的问题

### ISSUE THREAD

**Issue by garyvalue** [bigfa/Farallon#3]
文章如果没有包含图片会超出区域
![2023-10-18_163003.png](https://pic1.58cdn.com.cn/nowater/webim/big/n_v2aa7dcf54a33f4051b8f0c50d8869e651.png)
如果图片大小不一致会显得不对称
![2023-10-18_163301.png](https://pic7.58cdn.com.cn/nowater/webim/big/n_v2ed5c31c034c2402798ad5e244c8b280c.png)

**Comment by bigfa** [comment]
这个卡片样式本身就需要手动才能开启，因为这个卡片必须有大图支持才行，如果文章内容不符合要求还强制开启就只能是你截图这样了。。。

**Comment by bigfa** [comment]
溢出的问题已经修复了
