### ISSUE TITLE
首页显示问题

### ISSUE THREAD

**Issue by rambleryu** [bigfa/Farallon#7]
哥，我不太会改代码。

你这个首页设定是不是要自己设定呀，我没有改过其他设定是只能获取到第一篇文章。

默认的wp是展示最新文章。

图片显示是这样的情况。
<img width="1328" alt="image" src="https://github.com/bigfa/Farallon/assets/76433988/b9b4192e-a010-4b66-82e1-365a724efe66">

**Comment by bigfa** [comment]
看着像是php没开启mbstring

**Comment by rambleryu** [comment]
谢谢大佬，安装了php-mbstring已经正常了嘿嘿，谢谢佬。
